### ISSUE TITLE
Makefile clean (pull request lab)

### ISSUE THREAD

**Issue by vvostrikov10** [hunter-classes/fall-2022-135-lab-07-anitaprova#4]
I'll change the clean instruction from

clean:
	rm -f main main.o unindent.o indent.o 

to

clean:
	rm -f main *.o

It helps make sure that any .o file is deleted, so if the program ever expands you won't need to update the Makefile.

**Comment by anitaprova** [comment]
Sounds good, thanks for the helpful suggestion!
